version: "2.1"

services:
    db:
        image: mysql:5.7.22
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - ./db:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -h localhost -u root --password=MySQLRootPassword
            timeout: 20s
            retries: 10
        environment:
            MYSQL_DATABASE: dev
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: MySQLRootPassword
